### ISSUE TITLE
[BUG]  Autocomplete fields are not loading in production environment

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#243]
Right now, our staff label autocomplete widgets load in development, but not in production. this makes it hard to tag providers for following up with later.

**Describe the bug**

When you visit a hosting provider page, in development you see nice autocomplete widget from Django Autocomplete Light:

<img width="885" alt="Screenshot 2022-05-08 at 10 59 58" src="https://user-images.githubusercontent.com/17906/167289217-4d8d45ce-6412-4c7e-87f6-b98096ae2e97.png">

However, loading the same page with production mode on shows this unsightly select widget thing:

<img width="1044" alt="Screenshot 2022-05-08 at 11 00 36" src="https://user-images.githubusercontent.com/17906/167289227-8be40269-017f-4658-88a2-b28333951e6c.png">

**To Reproduce**

_Steps to reproduce the behavior:_

1. make sure you're using the appropriate environment (dev vs prod)
2. Go to a hosting provider page, i.e. `admin/accounts/hostingprovider/754/change/`
5. See error something like the screenshot above

**Expected behavior**

Both environments should be showing the autocomplete.

**Actual behavior**

Only production shows this.

**Visual proof**
If applicable, add visual proof to help explain your problem.

**Environment**

**Additional context**

There is this message in the browser console when loading in production:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'define')
    at dalLoadLanguage (en.0cbbd8d2522c.js:2:103)
    at autocomplete_light.min.8172b0a59e37.js:1:1007
    at autocomplete_light.min.8172b0a59e37.js:1:2942
```

This makes me think  that the widget is loading before jquery is available, or something similar.

I'm not sure why this would work in development but not production.

**Comment by mrchrisadams** [comment]
I think this is the thing we'd need to change - so we delay the calling of the autocomplete initialisation script until _after_ we are sure jquery and the rest are loaded.

https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#overriding-javascript-code

I _still_ don't know why it works in dev and not production, but hopefully when someone comes back to this, having this link will help.
