### ISSUE TITLE
[BUG] Developer documentation not building properly

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#293]
Our developer docs for this project should rebuild on each push to master, and be visible at https://docs.greenweb.org.

The build has started to break, and here's the error trace.

More information at the link [to the specific build](https://readthedocs.org/projects/greenweb/builds/17938599/)

```
Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/myst_parser/__init__.py", line 12, in setup
    from myst_parser.sphinx_parser import MystParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/myst_parser/sphinx_parser.py", line 15, in <module>
    from myst_parser.main import create_md_parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/myst_parser/main.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/greenweb/envs/latest/lib/python3.8/site-packages/myst_parser/main.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
The full traceback has been saved in /tmp/sphinx-err-7ywyuqr3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by mrchrisadams** [comment]
This is resolved now. We updated the dependencies and it's now working as intended.
